name: Jupyter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install scraper
        run: pip install -r requirements.txt

      - id: execute
        name: Execute Jupyter notebook
        run: jupyter execute download.ipynb
        shell: bash

      - id: commit
        name: Commit
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add *
          git commit -am "GH Action Headlines $(date)"
          git push origin main
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
        shell: bash
